on:
  workflow_dispatch:
  push:
    paths:
    - 'src/**/*'
    - 'test/**/*'
    - '.github/workflows/devcontainer-tests.yaml'

permissions:
  contents: read

jobs:
  test-install:
    continue-on-error: true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          - mssql-odbc
          - opentofu

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - run: |
        npm install -g @devcontainers/cli

    - run : |
         devcontainer features test -f ${{ matrix.features }}
