on:
  workflow_dispatch:
  push:
    paths:
    - 'src'
    - 'test'
    - '.github/workflows/devcontainer-tests.yaml'

  pull_request:
    paths:
      - 'src'
      - 'test'

permissions:
  contents: read

jobs:
  test-install:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        version_version: 18.x

    - run: |
        npm install

    - run : |
        export PATH=$PATH:$(pwd)/node_modules/.bin
        devcontainer features test . -q
